### ISSUE TITLE
Shader Complication error on Shadow Map Shader

### ISSUE THREAD

**Issue by Mustardnote3943** [ikemen-engine/Ikemen-GO#2116]
### Describe the bug

This error seems to be related to an OpenGL extension. My graphics are Intel UHD graphics, which are integrated graphics and are up to date on driver updates. I did a graphics test, and there were no issues, so the issue must be within the game engine's dev build.

### To Reproduce

this happened when I updated the Ikemen GO dev build

### Expected behavior

launched normally without any issue

### Screenshots / Video

here's the error prompt window: 
![image](https://github.com/user-attachments/assets/5c51195c-c86e-4f17-af6c-73ad1a054db7)

### Engine Version (or source code date)

DEV/NIGHTLY

### Operating system

Linux

**Comment by Eiton** [comment]
You can turn off the shadow at the moment under option->video settings->3d model settings.
Seems like linux drivers hate geometry shaders on GL 2.1. We plan to make the GL3.2 build available for Linux and Windows after fixing some issues. Hopefully the shadow map shader can be compiled on GL 3.2.

**Comment by Mustardnote3943** [comment]
thank you, I can't wait for the GL3.2 build of Ikemen GO. I love game engines.

**Comment by Mustardnote3943** [comment]
sorry, I closed it. reopened.

**Comment by Eiton** [comment]
The newest nightly includes a second executable Ikemen_GO_GL32.
Please try it.

**Comment by Mustardnote3943** [comment]
when I launched the regular ikemen go, it showed the error but ikemen go ignored the error and continued work as usual. but as of right now, I launched it today and after that error, I got another new error that'll close ikemen go. now for the GL32, it doesn't show the error about the shadow thing but then after that, the same new error that closes ikemen go from the normal version is on gl32 as well. just remembered, that I had this error previously, it happens when I have my Razer Huntsman mini keyboard plugged in. What's strange is when I press a key on the keyboard on ikemen go, it seems to do both actions which is move and select (not the menu button). so basically, I press but ikemen go thinks I'm pressing two buttons that both have a different action. here's the error:

ikemen.log:

runtime error: index out of range [1] with length 1
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1()
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1988 +0x212
panic({0x985420, 0xc0045873e0})
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
main.JoystickState(0x1, 0xa)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:224 +0x5ea
main.KeyConfig.U(...)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:322
main.(*InputReader).LocalInput(0x0?, 0x1)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:466 +0x708
main.(*CommandList).Input(0xc00083b200, 0x1, 0x1, 0x0?, 0x0)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/input.go:2113 +0x43c
main.systemScriptInit.func37(0xc000348430?)
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/script.go:704 +0xd1
github.com/yuin/gopher-lua.callGFunction(0xc00033c000, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:202 +0x37
github.com/yuin/gopher-lua.init.3.func26(0xc00033c000, 0xc080000?, 0xc00033e000?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:821 +0x379
github.com/yuin/gopher-lua.mainLoop(0xc00033c000, 0xc00078f080?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/vm.go:31 +0xfa
github.com/yuin/gopher-lua.(*LState).callR(0xc00033c000, 0x0, 0xffffffffffffffff, 0xc00031c128?)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1211 +0x1b4
github.com/yuin/gopher-lua.(*LState).Call(...)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0xc00033c000, 0x0, 0xc00078f080?, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/state.go:2030 +0x145
github.com/yuin/gopher-lua.(*LState).DoFile(0xc00033c000, {0xc000126870?, 0x0?})
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v1.1.0/auxlib.go:396 +0x6b
main.main()
	/home/runner/work/Ikemen-GO/Ikemen-GO/src/main.go:106 +0x278

stack traceback:
	[G]: in function 'commandInput'
	external/script/main.lua:115: in function 'f_cmdInput'
	external/script/main.lua:131: in function 'f_cmdBufReset'
	external/script/main.lua:3873: in function 'f_frameChange'
	external/script/main.lua:4094: in function 'f_menuCommonDraw'
	external/script/main.lua:3164: in function 'loop'
	external/script/main.lua:4220: in main chunk
	[G]: ?

**Comment by Eiton** [comment]
At least the shader compilation error is fixed.
This seems to be input device error. Have you plugged in any new input devices, joysticks? Is the previous nightly still working?

**Comment by Mustardnote3943** [comment]
This new error only occurs when my keyboard, "Razer Hunter Mini" is plugged in. I can run Ikemen Go, but I have to unplug the keyboard from my laptop.

**Comment by Eiton** [comment]
It would be better to close this issue and create a new issue about the input device error.

**Comment by Orochikyocr** [comment]
Sorry for the bump. In my system, Lubuntu 22.04, on a Laptop with Radeon Vega 7, the Ikemen_GO_Linux_GL32 won't launch. It immediately crashes to the desktop.

Got this huge error message when launching from terminal
https://pastebin.com/uttALy1k

Updated: Tested on Intel HD 4000, same result, crash to desktop after launching.

**Comment by Mustardnote3943** [comment]
Yeah Gl32 no longer opens

**Comment by K4thos** [comment]
gl3.2 build on nightly is broken for everyone after merging the batch rendering commit, just wait until fantasma fixes the issues.

**Comment by Kasasagi77** [comment]
Is having a whole separate build variant really the best way to solve this problem?

Could it possibly done automatically at runtime by some conditional code chcecking for the (non)existence of these particular OpenGL extensions?

**Comment by Mustardnote3943** [comment]
When the gl32 came around, I noticed I can launch the normal version but an error occurs but it continues to run without ikemen go closing out.
